name: Deploy Event Bus

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your desired AWS region

    - name: Deploy Event Bus
      run: |
        aws cloudformation create-stack \
          --stack-name my-event-bus-stack \
          --template-body file:///full/absolute/path/to/your/template.yaml # Replace with the actual path to your CloudFormation template
          --parameters ParameterKey=EventBusName,ParameterValue=demo02 # Set the event bus name
          --capabilities CAPABILITY_NAMED_IAM
      env:
        AWS_DEFAULT_REGION: us-east-1 # Replace with your desired AWS region
