name: Create EventBridge Event Bus

on:
  push:
    branches:
      - main

jobs:
  create-event-bus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Create EventBridge Event Bus
        run: |
          aws events create-event-bus --name demohello02 # Set the event bus name
